"""UC3 demand_forecasts

Revision ID: 1a325eb44672
Revises: 27d41d0a0d09
Create Date: 2026-04-27 18:58:04.441667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1a325eb44672'
down_revision: Union[str, None] = '27d41d0a0d09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demand_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('predicted_kwh', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_demand_forecasts_zone_ts', 'demand_forecasts', ['zone_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_demand_forecasts_zone_ts', table_name='demand_forecasts')
    op.drop_table('demand_forecasts')
    # ### end Alembic commands ###
