"""UC2 occupancy records

Revision ID: 27d41d0a0d09
Revises: dd4308dcc564
Create Date: 2026-04-19 18:23:42.976103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '27d41d0a0d09'
down_revision: Union[str, None] = 'dd4308dcc564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('occupancy_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('occupancy_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_occupancy_records_zone_id'), 'occupancy_records', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_occupancy_records_zone_id'), table_name='occupancy_records')
    op.drop_table('occupancy_records')
    # ### end Alembic commands ###
